export const GET_SUPPLIER_RFP = 'GET_SUPPLIER_RFP';
export const SET_CURRENT_SUPPLIER_RFP = 'SET_CURRENT_SUPPLIER_RFP';
export const CREATE_BID_RESPONSE = 'CREATE_BID_RESPONSE';
export const FIND_SUPPLIER_EVENT_BY_ID = 'FIND_SUPPLIER_EVENT_BY_ID';
