export const GET_SUPPLIER_RFP = 'GET_SUPPLIER_RFP';
export const SET_CURRENT_SUPPLIER_RFP = 'SET_CURRENT_SUPPLIER_RFP';
export const CREATE_BID_RESPONSE = 'CREATE_BID_RESPONSE';
export const FIND_SUPPLIER_EVENT_BY_ID = 'FIND_SUPPLIER_EVENT_BY_ID';
export const GET_SUPPLIER_RFP_BY_ID = 'GET_SUPPLIER_RFP_BY_ID';
export const CLEAR_CURRENT_RFP = 'CLEAR_CURRENT_RFP';
export const CONFIRM_RSVP = 'CONFIRM_RSVP';
export const REVOKE_RSVP = 'REVOKE_RSVP';
export const ACCEPT_RFP_TERMS = 'ACCEPT_RFP_TERMS';
// check whether the supplier has sent an RSVP or has acccepted terms and conditions
export const CHECK_SUPPLIER_CLAIMS = 'CHECK_SUPPLIER_CLAIMS';
export const SET_SUPPLIER_LOADING = 'SET_SUPPLIER_LOADING';
export const SET_SUPPLIER_DONE_LOADING = 'SET_SUPPLIER_DONE_LOADING';
export const VIEW_BIDS = 'VIEW_BIDS';
