// supplier UI actions
export const LOADING_ANALYTICS = 'LOADING_ANALYTICS';
export const ANALYTICS_DONE_LOADING = 'ANALYTICS_DONE_LOADING';
export const LOADING_RECENT_ACTIVITIES = 'LOADING_RECENT_ACTIVITIES';
export const RECENT_ACTIVITIES_DONE_LOADING = 'RECENT_ACTIVITIES_DONE_LOADING';
export const LOADING_BIDS = 'LOADING_BIDS';
export const BIDS_DONE_LOADING = 'BIDS_DONE_LOADING';
export const LOADING_RSVP_CLOSING_SOON = 'LOADING_RSVP_CLOSING_SOON';
export const RSVP_CLOSING_SOON_DONE_LOADING = 'RSVP_CLOSING_SOON_DONE_LOADING';
export const LOADING_BIDS_CLOSING_SOON = 'LOADING_BIDS_CLOSING_SOON';
export const BIDS_CLOSING_SOON_DONE_LOADING = 'BIDS_CLOSING_SOON_DONE_LOADING';
export const LOADING_SUPPLIER_RFP_CLOSING_SOON = 'LOADING_SUPPLIER_RFP_CLOSING_SOON';
export const SUPPLIER_RFP_CLOSING_DONE_LOADING = 'SUPPLIER_RFP_CLOSING_DONE_LOADING';


// buyer UI action
export const IS_PUBLISHING_RFP = 'IS_PUBLISHING_RFP';
export const DONE_PUBLISHING_RFP = 'DONE_PUBLISHING_RFP';
